services:
  db:
    build: ./db
    shm_size: 256mb
    container_name: byte-spot-db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - byte-spot-db:/var/lib/postgresql
  api:
    build: ./api
    ports:
      - "3000:3000"
volumes:
  byte-spot-db:
